server:
  port: 8088

spring:  #config server configuration
  application:
    name: post-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkatram64/my-ms-centralized-config.git
          search-paths: config  # Correct for your directory structure
          clone-on-start: true   # Ensures config is pulled on startup
          default-label: main    # Default git branch
          force-pull: true       # Recommended to get latest changes

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.context.config: TRACE
