server:
  port: ${CONTENT_SERVICE_SERVER_PORT:8082}

management: #actuator configuration
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:  #for zipkin logging
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      #base-url: http://zipkin-server:9411
      endpoint: http://zipkin-server:9411/api/v2/spans  # Explicit endpoint
      #base-url: http://localhost:9411

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:content-mysql}:3308/content_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:  #database connection pool configuration
      connection-timeout: 15000
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 10000
      max-lifetime: 50000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  output:
    ansi:
      enabled: always

eureka: #client is registering into Eureka server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://service-registry-in-eureka:8761/eureka/
  instance:
    hostname: ${spring.application.name}
    instanceId: ${spring.application.name}:${server.port}



#secret for creating JWT token, JWT token will live upto 10 hours
jwtSecret: b6c3e9153b2ae05e5b20444bbf014ab0dba5cfac666117d767dbd284b825ed85
expirationInMs: 36000000  # 10(hours) * 60(minutes) * 60(seconds) * 1000(milli seconds) = 36000000