server:
  port: 8761

spring:
  application:
    name: service-registry-in-eureka
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  output:
    ansi:
      enabled: always

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    wait-time-in-ms-when-sync-empty: 0
